[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
El objetivo  del proyecto es la creación de un sistema descentralizado de gestión de rutas basado en las especificaciones SOLID, en la que lo más importante será la privacidad de los datos y el control de los mismos por los usuarios.
****

=== Requirements Overview

[role="arc42help"]
****
* El sistema debe utilizar una arquitectura descentralizada, separando datos y aplicación.
* Los usuarios deben poder ver sus rutas en un mapa.
* Los datos de las rutas se deben guardar en los PODs de los usuarios.
* Los usuarios pueden tener amigos con los que compartir sus rutas.
* El usuario puede recibir notificaciones cuando le compartan una ruta.
* Los usuarios pueden compartir fotos, videos u otros ficheros con sus amigos.

* Deben de poder verse las rutas  cargadas por usuarios de otros programas de gestión de rutas, teniendo en cuenta la interoperabilidad.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
