[[section-design-decisions]]
== Design Decisions


****

En la siguiente tabla se enumeran las decisiones que hemos tomado para implementar en nuestro proyecto en cuanto a arquitectura y diseño.

[options="header",cols="1,2"]
|===
|Herramienta|Motivos
| Solid | Cómodo para los usuarios ya que le dan permiso a las personas y a sus aplicaciones para leer o escribir en partes de su Solid POD. Por lo tanto, cada vez que abra una nueva aplicación, no tendrá que completar sus datos nunca más.

Otra ventaja es la protección de la privacidad del usuario gracias a esta herramienta.
| React
|Nos permite un desarrollo ágil, ordenado y con una arquitectura focalizada en componentes y fácil de mantener ya que los errores sucederán en la propia funcionalidad del componente o en la comunicación con los demás.
| Git
| Facilita el trabajo colaborativo.

Reduce considerablemente los tiempos de despliegue de un proyecto.

Permite regresar a versiones anteriores de forma sencilla y muy rápida.

Las "branches" o ramas, permiten trabajar con una base de código paralela al proyecto en sí, donde podemos corregir bugs o desarrollar nuevas características para el producto sin afectar el "master", pero manteniendo todas las ventajas de usar un sistema de control de versiones.

Empezar a trabajar desde otro entorno es tan fácil como "clonar" el proyecto a tu nuevo entorno.

Proporciona un sistema de etiquetas, para etiquetar las distintas versiones del proyecto.
| Arc42
| Nos proporciona una plantilla con los principales puntos para documentar la arquitectura software de nuestra aplicación web.
| AsciiDoctor
| Sistema de documentación dinámico y con sintaxis clara que nos permite mantener actualizada la documentación.


|===
****