package viade_es5b

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class PruebaCrearRuta extends Simulation {

	val httpProtocol = http
		.baseUrl("http://localhost:3000")
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3")
		.userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
		"Cache-Control" -> "max-age=0",
		"If-None-Match" -> """W/"a3e-AnfbrcfazmnwlfKdCBuPqjvjg6k"""",
		"Upgrade-Insecure-Requests" -> "1")

	val headers_1 = Map(
		"Cache-Control" -> "max-age=0",
		"If-None-Match" -> """W/"7cc6-x4NbkmGzr0X8QdYy/odqYe+ado0"""")

	val headers_2 = Map(
		"Cache-Control" -> "max-age=0",
		"If-None-Match" -> """W/"5bf47-ikTvqZw7tPZHkFqXCt/lqOk8GbE"""")

	val headers_3 = Map(
		"Cache-Control" -> "max-age=0",
		"If-None-Match" -> """W/"f2fb82-xi770ARvF9mJNc/C9S9KP9oECvA"""")

	val headers_4 = Map("If-None-Match" -> """W/"5c66f-/LzIpIZw9QoyRxgUzDFSPFEw6TA"""")

	val headers_5 = Map("If-None-Match" -> """W/"f2fc41-o/jIw+Pbr29CJAjeUvD1FXMqHyc"""")

	val headers_6 = Map("If-None-Match" -> """W/"39bda-wavS+3Bu5Q9112glPTfSvZ4R6T8"""")

	val headers_7 = Map("If-None-Match" -> """W/"e4536c-SpoORa+kY+8Y6JBy6H+ZKU3QQkg"""")

	val headers_10 = Map("If-None-Match" -> """W/"3a9ee-mhqPv6TERE615jNa0iJFxyYBwMY"""")

	val headers_11 = Map("If-None-Match" -> """W/"e53948-Wfinw5N5NVOpPam7Ht+0nabVT+c"""")



	val scn = scenario("PruebaCrearRuta")
		.exec(http("PruebaCrearRuta_0")
			.get("/")
			.headers(headers_0))
		.exec(http("PruebaCrearRuta_1")
			.get("/viade_es5b/static/js/bundle.js")
			.headers(headers_1))
		.exec(http("PruebaCrearRuta_2")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_2))
		.exec(http("PruebaCrearRuta_3")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_3))
		.pause(12)
		.exec(http("PruebaCrearRuta_4")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_5")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_6")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_6))
		.pause(140 milliseconds)
		.exec(http("PruebaCrearRuta_7")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_7))
		.pause(9)
		.exec(http("PruebaCrearRuta_8")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_9")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_10")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(130 milliseconds)
		.exec(http("PruebaCrearRuta_11")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(9)
		.exec(http("PruebaCrearRuta_12")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_13")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_14")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(170 milliseconds)
		.exec(http("PruebaCrearRuta_15")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(13)
		.exec(http("PruebaCrearRuta_16")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_17")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_18")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(127 milliseconds)
		.exec(http("PruebaCrearRuta_19")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(9)
		.exec(http("PruebaCrearRuta_20")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_21")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_22")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(160 milliseconds)
		.exec(http("PruebaCrearRuta_23")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(9)
		.exec(http("PruebaCrearRuta_24")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_25")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_26")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(173 milliseconds)
		.exec(http("PruebaCrearRuta_27")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(9)
		.exec(http("PruebaCrearRuta_28")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_29")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_30")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(133 milliseconds)
		.exec(http("PruebaCrearRuta_31")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(9)
		.exec(http("PruebaCrearRuta_32")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_33")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_34")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(130 milliseconds)
		.exec(http("PruebaCrearRuta_35")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))
		.pause(11)
		.exec(http("PruebaCrearRuta_36")
			.get("/viade_es5b/static/js/main.chunk.js")
			.headers(headers_4))
		.exec(http("PruebaCrearRuta_37")
			.get("/viade_es5b/static/js/0.chunk.js")
			.headers(headers_5))
		.exec(http("PruebaCrearRuta_38")
			.get("/viade_es5b/static/js/main.chunk.js.map")
			.headers(headers_10))
		.pause(146 milliseconds)
		.exec(http("PruebaCrearRuta_39")
			.get("/viade_es5b/static/js/0.chunk.js.map")
			.headers(headers_11))

	setUp(scn.inject(atOnceUsers(50))).protocols(httpProtocol)
}